export const data = [
  {
    id: 1,
    title: "Buckle Handbag 1",
    image: "https://5.imimg.com/data5/CO/XW/MY-44197581/ladies-stylish-purse.jpg",
    price: "22.00$",
    category: "handBags",
    subCat : "Purse",
  },
  {
    id: 2,
    title: "Buckle Handbag 2",
    image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRj1Bsx_JUni5HgqZJhFSK2IcqonalFiI12a4g64UWWR5HHGy7AZqb7eG7T2k3WtkI8-Ek&usqp=CAU",
    price: "22.00$",
    category: "handBags",
    subCat : "Purse",
  },
  {
    id: 3,
    title: "Buckle Handbag 3",
    image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTX7b4nFEqmbOQwH4qXK6sTeCkFn8JCb1jFTRwCKV8akr0fYqPwrvieCNM6HAWXDmjZimY&usqp=CAU",
    price: "22.00$",
    category: "handBags",
    subCat : "Purse",
  },
  {
    id: 4,
    title: "Buckle Handbag 4",
    image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTVGZN0TOhsx4G_D6avavHSFYhW3YiW-cM5ex2E-mAJgfZbud1ieMDDCZdet3Eqw1nte5Q&usqp=CAU",
    price: "22.00$",
    category: "handBags",
    subCat : "Purse",
  },
  {
    id: 5,
    title: "Buckle Handbag 5",
    image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRzrZbjKmA8wQAOQT6wRRMTNJ6u3KjGjjxYQAv_MtcMVXQroOALfay5miUuuc_jmFbrw8g&usqp=CAU",
    price: "22.00$",
    category: "handBags",
    subCat : "Purse",
  },
  {
    id: 6,
    title: "Buckle Handbag 6",
    image: 'https://png.pngtree.com/png-vector/20241230/ourmid/pngtree-trendy-women-s-handbags-and-purses-for-every-occasion-png-image_14975126.png',
    price: "22.00$",
    category: "handBags",
    subCat : "Purse",
  },
  {
    id: 7,
    title: "Buckle Handbag 7",
    image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQwFg2ptkgB9dYyDiLlpVw_jRZ6LGOpxIMzikhU1j6PhTuMW9owEaIMHQpSq73nVNIW7UM&usqp=CAU",
    price: "22.00$",
    category: "handBags",
    subCat : "Purse",
  },
  {
    id: 8,
    title: "Buckle Handbag 8",
    image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTqcnpdmjxb0QL8Nkw-fRoALw_bBgmjmZRxSQb7IP6uAsv_LyMHJQx8LEnAmJuwigCt8nY&usqp=CAU",
    price: "22.00$",
    category: "handBags",
    subCat : "Purse",
  },
  {
    id: 9,
    title: "Buckle Handbag 9",
    image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRV1Ap2L5Yuay1YhSkC3iOsHGZx8aJ5fuxgySdPSQvAzNkbz4xJHXR109D3sGNwEzeI3Ig&usqp=CAU",
    price: "22.00$",
    category: "handBags",
    subCat : "Purse",
  },

  {
    id: 10,
    title: "Buckal Handbag",
    image: 'https://media.istockphoto.com/id/654113018/photo/orange-handbag-on-emerald-green-background.jpg?s=612x612&w=0&k=20&c=RVpc7QXNgBIm_gYjYc53XdtHM07F8WEXIKxmjVNPDL4=',
    price: '22.00$',
    category: "brandBags",
    subCat : "Purse",
  },
  {
    id: 11,
    title: "Diane Handbag",
    image: 'https://t3.ftcdn.net/jpg/08/60/85/30/360_F_860853099_feiJPkIHfUaaMbZUHBSerr0wnwcFZBcp.jpg',
    price: '49.00$',
    category: "brandBags",
    subCat : "Purse",
  },
  {
    id: 12,
    title: "Diyana Handbag",
    image: 'https://media.istockphoto.com/id/654113018/photo/orange-handbag-on-emerald-green-background.jpg?s=612x612&w=0&k=20&c=RVpc7QXNgBIm_gYjYc53XdtHM07F8WEXIKxmjVNPDL4=',
    price: '2.00$',
    category: "brandBags",
    subCat : "Purse",
  },
  {
    id: 13,
    title: "Flap Over",
    image: 'https://t3.ftcdn.net/jpg/08/39/70/68/360_F_839706855_bkEqXgFv0UUOvR5R8mp9Isx4AMTEfriw.jpg',
    price: '49.00$',
    category: "brandBags",
    subCat : "Purse",
  },


  
  {
    id: 14,
    title: "Lucy Hangbag",
    image: 'https://media.istockphoto.com/id/1061199048/vector/stylish-womens-beige-handbag.jpg?s=612x612&w=0&k=20&c=ikrH5_Gz5x1j8Vf2wEUj4SXbsjxH9OVAqgmpKiGX7TY=',
    price: '49.00$',
    category: "JanicaHandBags",
    subCat : "Purse",
  },
  {
    id: 15,
    title: "Rucy Hangbag",
    image: 'https://media.istockphoto.com/id/1365118618/photo/blue-fashion-purse-handbag-on-white-background-isolated.jpg?s=612x612&w=0&k=20&c=VNszfC0cxenqZGhjlr3gqqvzHWREuhdY_H3CKF1B38g=',
    price: '49.00$',
    category: "JanicaHandBags",
    subCat : "Purse",
  },
  {
    id: 16,
    title: "Justy Hangbag",
    image: 'https://cdn-images.farfetch-contents.com/15/76/83/45/15768345_28790830_600.jpg',
    price: '49.00$',
    category: "JanicaHandBags",
    subCat : "Purse",
  },
  {
    id: 17,
    title: "Dusty Hangbag",
    image: 'https://assets.ajio.com/medias/sys_master/root/20231107/hoXZ/654a5da5ddf779151975eac4/-473Wx593H-410407304-100-MODEL.jpg',
    price: '49.00$',
    category: "JanicaHandBags",
    subCat : "Purse",
  },
  {
    id: 18,
    title: "Nisty Hangbag",
    image: 'https://png.pngtree.com/png-clipart/20250127/original/pngtree-designer-women-purses-and-luxury-handbag-collection-png-image_20059295.png',
    price: '49.00$',
    category: "JanicaHandBags",
    subCat : "Purse",
  },
  {
    id: 19,
    title: "Nikku Hangbag",
    image: 'https://png.pngtree.com/png-vector/20241230/ourmid/pngtree-trendy-women-s-handbags-and-purses-for-every-occasion-png-image_14975126.png',
    price: '49.00$',
    category: "JanicaHandBags",
    subCat : "Purse",
  },
  {
    id: 20,
    title: "Stimmy Hangbag",
    image: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcR9KIRorgf2j-YL7AZA-yZP_oxn1_z8OZVEZO4hlI9tggpnEFsy2j2gmh61TJMxl_D9Xnw&usqp=CAU',
    price: '49.00$',
    category: "JanicaHandBags",
    subCat : "Purse",
  },
  {
    id: 21,
    title: "Nekla Hangbag",
    image: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTRVyiiHQDdPDNw4heBV_utfnnjneGGdfnrszIlNcz8fFr3jXSj12zFRAyIRnfzsj2QBt4&usqp=CAU',
    price: '49.00$',
    category: "JanicaHandBags",
    subCat : "Purse",
  },
]